# Site settings
title:          Java -> C++
description:    "Quickly become familiar with the unique features of C++"
url:            "http://localhost:4000"

# Author
author:
  name:         Alec Chan
  url:          http://alecchan.io
  email:        me@alecchan.io

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink:      /:title
paginate:       5
